name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
          DEBIAN_FRONTEND=noninteractive apt-get install -y git zip unzip openjdk-17-jdk python3-pip python3.9 python3.9-dev python3.9-venv autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev automake
          update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1

      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython legacy-cgi

      - name: Build APK
        run: |
          export ANDROIDSDK=/root/.buildozer/android/platform/android-sdk
          export ANDROIDNDK=/root/.buildozer/android/platform/android-ndk-r25c
          export ANDROIDAPI=33
          export ANDROIDMINAPI=24
          export PATH=$PATH:/root/.buildozer/android/platform/apache-ant-1.9.4/bin
          yes | buildozer android debug || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gofroagregat-apk
          path: bin/*.apk
